version: "3.8"
services:
  sql:
    container_name: pokemon_sqlserver_local
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pokemon123